spring.application.name=POD

# ===============================

# DATABASE CONFIGURATION

# ===============================

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.pibgfuzfkhanmxifnqgj
spring.datasource.password=Z3ScdvOAF0zVJtvA
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================

# HIKARI CONNECTION POOL

# ===============================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=180000

# ===============================

# JPA / HIBERNATE

# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase pooler optimization

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

brevo.api.key=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
brevo.sender.email=dixitgauravkumar69@gmail.com